name: Deploy Frontend to Vercel

env:
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Linting
        run: npm run lint:fix

      - name: Run tests
        run: npm test -- --passWithNoTests

      - name: Build Project
        run: npm run build
        env:
          CI: false

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name : Pull Vercel Enviroment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }} 

      - name: Deploy to Vercel
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} 
      
      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        