name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Lisää nämä ympäristömuuttujat koko job-tasolle
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Linting
        run: npm run lint:fix

      - name: Run tests
        run: npm test -- --passWithNoTests

      - name: Build Project
        run: npm run build
        env:
          CI: false

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Create Vercel Config
        # Luo konfiguraatiotiedoston Vercel projektille
        run: |
          mkdir -p .vercel
          echo '{"orgId":"'"$VERCEL_ORG_ID"'","projectId":"'"$VERCEL_PROJECT_ID"'"}' > .vercel/project.json

      - name: Pull Vercel Environment Information
        # Korjattu tokeni-syntaksi
        run: vercel pull --yes --environment=production --token="$VERCEL_TOKEN"

      - name: Build for Vercel
        # Korjattu tokeni-syntaksi
        run: vercel build --prod --token="$VERCEL_TOKEN"
      
      - name: Deploy to Vercel
        # Korjattu tokeni-syntaksi
        run: vercel deploy --prebuilt --prod --token="$VERCEL_TOKEN"
